<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Parallel test suite" duration-ms="14261" started-at="2017-05-15T17:59:55Z" finished-at="2017-05-15T18:00:10Z">
    <groups>
      <group name="functest">
        <method signature="SimpleTest.loginTest()[pri:0, instance:SimpleTest@39aeed2f]" name="loginTest" class="SimpleTest"/>
        <method signature="SimpleTest.testMethod1(java.lang.String)[pri:0, instance:SimpleTest@39aeed2f]" name="testMethod1" class="SimpleTest"/>
      </group> <!-- functest -->
    </groups>
    <test name="Test1" duration-ms="14261" started-at="2017-05-15T17:59:55Z" finished-at="2017-05-15T18:00:10Z">
      <class name="SimpleTest">
        <test-method status="PASS" signature="loginTest()[pri:0, instance:SimpleTest@39aeed2f]" name="loginTest" duration-ms="11551" started-at="2017-05-15T20:59:55Z" finished-at="2017-05-15T21:00:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="testMethod1(java.lang.String)[pri:0, instance:SimpleTest@39aeed2f]" name="testMethod1" duration-ms="2680" started-at="2017-05-15T21:00:07Z" finished-at="2017-05-15T21:00:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[This is the value for a parameter]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at SimpleTest.testMethod1(SimpleTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
      </class> <!-- SimpleTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Parallel test suite -->
</testng-results>
